Importing classes

In [1]:
import pandas as pd # type: ignore
import numpy as np # type: ignore
import seaborn as sns # type: ignore
from sqlalchemy import create_engine # type: ignore

engine = create_engine('postgresql://renan@localhost:5432/main')
sql = '''
    select * from flightsearcher.summary_view;
'''
df = pd.read_sql_query(sql,con=engine)
dfFilter = df.copy() #[
    #(df['origin_country'] != 'Usa') &
    #(df['destiny_country'] != 'Usa') &
    #(df['origin_country'] != 'Canada') 
    #(df['destiny_country'] != 'Canada')
#]
dfFilter[['hours','minutes_raw']] = dfFilter.duration.str.split('h',expand=True)
dfFilter['minutes'] = dfFilter.minutes_raw.str.extract('(\d+)')
dfFilter['total_hours'] = dfFilter['hours'].astype(float) + dfFilter['minutes'].astype(float)/60
originSP = dfFilter[dfFilter['origin_city']=='Sao Paulo']
destinySP = dfFilter[dfFilter['destiny_city']=='Sao Paulo']
lane = originSP.merge(destinySP, left_on ='destiny_city', right_on='origin_city',how='inner',suffixes=('_ida','_volta'))
lane['total_price'] = lane['price_ida'] * 0.8 + lane['price_volta']  * 0.8
lane['total_hours'] = lane['total_hours_ida'] + lane['total_hours_volta']
lane['price_per_hour'] = lane['total_price'] / lane['total_hours']
lane['price_for_two'] = lane['total_price'] * 2
lane['12_times_price'] = lane['total_price'] / 12
lane['12_times_price_for_two'] = lane['price_for_two'] / 12

<>:18: SyntaxWarning: invalid escape sequence '\d'
<>:18: SyntaxWarning: invalid escape sequence '\d'
/var/folders/fl/p4l8bsq558ddd789fk6x4l340000gn/T/ipykernel_55484/2618982914.py:18: SyntaxWarning: invalid escape sequence '\d'
  dfFilter['minutes'] = dfFilter.minutes_raw.str.extract('(\d+)')

In [3]:
lane[
    (lane['destiny_country_ida']=='Spain') &
    (lane['travel_date_volta'] > lane['travel_date_ida'])
].pivot_table(index='travel_date_ida',columns='travel_date_volta',values='price_for_two',aggfunc='min',margins=True).style.background_gradient(cmap='coolwarm',axis=None).format("{:.2f}")

In [4]:

lane[
    (lane['destiny_country_ida']=='Spain') &
    (lane['travel_date_volta'].astype(str) == '2025-03-14') &
    (lane['travel_date_ida'].astype(str) == '2025-03-05')
][[
    'travel_date_ida'
    ,'travel_date_volta'
    ,'companies_ida'
    ,'companies_volta'
    ,'price_ida'
    ,'price_volta'
    ,'total_hours_ida'
    ,'total_hours_volta'
    ,'total_price'
    ,'total_hours'
    ,'price_per_hour'
    ,'price_for_two'
    ,'12_times_price'
    ,'12_times_price_for_two'
]]

,travel_date_ida,travel_date_volta,companies_ida,companies_volta,price_ida,price_volta,total_hours_ida,total_hours_volta,total_price,total_hours,price_per_hour,price_for_two,12_times_price,12_times_price_for_two
138130,2025-03-05,2025-03-14,Avianca,Turkish,2534.0,2489.0,20.166667,31.750000,4018.4,51.916667,77.400963,8036.8,334.866667,669.733333
138131,2025-03-05,2025-03-14,Avianca,Turkish,2534.0,2489.0,20.166667,33.333333,4018.4,53.500000,75.110280,8036.8,334.866667,669.733333
138132,2025-03-05,2025-03-14,Avianca,Avianca,2534.0,2545.0,20.166667,20.666667,4063.2,40.833333,99.506939,8126.4,338.600000,677.200000
138133,2025-03-05,2025-03-14,Avianca,Avianca and Gol,2534.0,2652.0,20.166667,22.583333,4148.8,42.750000,97.047953,8297.6,345.733333,691.466667
138134,2025-03-05,2025-03-14,Avianca,Tap,2534.0,2735.0,20.166667,17.333333,4215.2,37.500000,112.405333,8430.4,351.266667,702.533333
138135,2025-03-05,2025-03-14,Avianca,Lufthansa,2534.0,2858.0,20.166667,15.500000,4313.6,35.666667,120.942056,8627.2,359.466667,718.933333
138136,2025-03-05,2025-03-14,Avianca,Tap,2534.0,3305.0,20.166667,13.333333,4671.2,33.500000,139.438806,9342.4,389.266667,778.533333
138137,2025-03-05,2025-03-14,Avianca,Iberia,2534.0,4802.0,20.166667,13.333333,5868.8,33.500000,175.188060,11737.6,489.066667,978.133333
138404,2025-03-05,2025-03-14,Tap,Turkish,2810.0,2489.0,17.083333,31.750000,4239.2,48.833333,86.809556,8478.4,353.266667,706.533333
138405,2025-03-05,2025-03-14,Tap,Turkish,2810.0,2489.0,17.083333,33.333333,4239.2,50.416667,84.083306,8478.4,353.266667,706.533333
138406,2025-03-05,2025-03-14,Tap,Avianca,2810.0,2545.0,17.083333,20.666667,4284.0,37.750000,113.483444,8568.0,357.000000,714.000000
138407,2025-03-05,2025-03-14,Tap,Avianca and Gol,2810.0,2652.0,17.083333,22.583333,4369.6,39.666667,110.157983,8739.2,364.133333,728.266667
138408,2025-03-05,2025-03-14,Tap,Tap,2810.0,2735.0,17.083333,17.333333,4436.0,34.416667,128.891041,8872.0,369.666667,739.333333
138409,2025-03-05,2025-03-14,Tap,Lufthansa,2810.0,2858.0,17.083333,15.500000,4534.4,32.583333,139.163171,9068.8,377.866667,755.733333
138410,2025-03-05,2025-03-14,Tap,Tap,2810.0,3305.0,17.083333,13.333333,4892.0,30.416667,160.832877,9784.0,407.666667,815.333333
138411,2025-03-05,2025-03-14,Tap,Iberia,2810.0,4802.0,17.083333,13.333333,6089.6,30.416667,200.206027,12179.2,507.466667,1014.933333
138678,2025-03-05,2025-03-14,ITA,Turkish,3096.0,2489.0,15.250000,31.750000,4468.0,47.000000,95.063830,8936.0,372.333333,744.666667
138679,2025-03-05,2025-03-14,ITA,Turkish,3096.0,2489.0,15.250000,33.333333,4468.0,48.583333,91.965695,8936.0,372.333333,744.666667
138680,2025-03-05,2025-03-14,ITA,Avianca,3096.0,2545.0,15.250000,20.666667,4512.8,35.916667,125.646404,9025.6,376.066667,752.133333
138681,2025-03-05,2025-03-14,ITA,Avianca and Gol,3096.0,2652.0,15.250000,22.583333,4598.4,37.833333,121.543612,9196.8,383.200000,766.400000
138682,2025-03-05,2025-03-14,ITA,Tap,3096.0,2735.0,15.250000,17.333333,4664.8,32.583333,143.165217,9329.6,388.733333,777.466667
138683,2025-03-05,2025-03-14,ITA,Lufthansa,3096.0,2858.0,15.250000,15.500000,4763.2,30.750000,154.900813,9526.4,396.933333,793.866667
138684,2025-03-05,2025-03-14,ITA,Tap,3096.0,3305.0,15.250000,13.333333,5120.8,28.583333,179.153353,10241.6,426.733333,853.466667
138685,2025-03-05,2025-03-14,ITA,Iberia,3096.0,4802.0,15.250000,13.333333,6318.4,28.583333,221.051895,12636.8,526.533333,1053.066667
138952,2025-03-05,2025-03-14,Tap,Turkish,3104.0,2489.0,15.416667,31.750000,4474.4,47.166667,94.863604,8948.8,372.866667,745.733333
138953,2025-03-05,2025-03-14,Tap,Turkish,3104.0,2489.0,15.416667,33.333333,4474.4,48.750000,91.782564,8948.8,372.866667,745.733333
138954,2025-03-05,2025-03-14,Tap,Avianca,3104.0,2545.0,15.416667,20.666667,4519.2,36.083333,125.243418,9038.4,376.600000,753.200000
138955,2025-03-05,2025-03-14,Tap,Avianca and Gol,3104.0,2652.0,15.416667,22.583333,4604.8,38.000000,121.178947,9209.6,383.733333,767.466667
138956,2025-03-05,2025-03-14,Tap,Tap,3104.0,2735.0,15.416667,17.333333,4671.2,32.750000,142.632061,9342.4,389.266667,778.533333
138957,2025-03-05,2025-03-14,Tap,Lufthansa,3104.0,2858.0,15.416667,15.500000,4769.6,30.916667,154.272776,9539.2,397.466667,794.933333
138958,2025-03-05,2025-03-14,Tap,Tap,3104.0,3305.0,15.416667,13.333333,5127.2,28.750000,178.337391,10254.4,427.266667,854.533333
138959,2025-03-05,2025-03-14,Tap,Iberia,3104.0,4802.0,15.416667,13.333333,6324.8,28.750000,219.993043,12649.6,527.066667,1054.133333
139226,2025-03-05,2025-03-14,LATAM and Vueling,Turkish,3132.0,2489.0,14.583333,31.750000,4496.8,46.333333,97.053237,8993.6,374.733333,749.466667
139227,2025-03-05,2025-03-14,LATAM and Vueling,Turkish,3132.0,2489.0,14.583333,33.333333,4496.8,47.916667,93.846261,8993.6,374.733333,749.466667
139228,2025-03-05,2025-03-14,LATAM and Vueling,Avianca,3132.0,2545.0,14.583333,20.666667,4541.6,35.250000,128.839716,9083.2,378.466667,756.933333
139229,2025-03-05,2025-03-14,LATAM and Vueling,Avianca and Gol,3132.0,2652.0,14.583333,22.583333,4627.2,37.166667,124.498655,9254.4,385.600000,771.200000
139230,2025-03-05,2025-03-14,LATAM and Vueling,Tap,3132.0,2735.0,14.583333,17.333333,4693.6,31.916667,147.057963,9387.2,391.133333,782.266667
139231,2025-03-05,2025-03-14,LATAM and Vueling,Lufthansa,3132.0,2858.0,14.583333,15.500000,4792.0,30.083333,159.290859,9584.0,399.333333,798.666667
139232,2025-03-05,2025-03-14,LATAM and Vueling,Tap,3132.0,3305.0,14.583333,13.333333,5149.6,27.916667,184.463284,10299.2,429.133333,858.266667
139233,2025-03-05,2025-03-14,LATAM and Vueling,Iberia,3132.0,4802.0,14.583333,13.333333,6347.2,27.916667,227.362388,12694.4,528.933333,1057.866667
139500,2025-03-05,2025-03-14,Air,Turkish,3276.0,2489.0,13.833333,31.750000,4612.0,45.583333,101.177331,9224.0,384.333333,768.666667
139501,2025-03-05,2025-03-14,Air,Turkish,3276.0,2489.0,13.833333,33.333333,4612.0,47.166667,97.780919,9224.0,384.333333,768.666667
139502,2025-03-05,2025-03-14,Air,Avianca,3276.0,2545.0,13.833333,20.666667,4656.8,34.500000,134.979710,9313.6,388.066667,776.133333
139503,2025-03-05,2025-03-14,Air,Avianca and Gol,3276.0,2652.0,13.833333,22.583333,4742.4,36.416667,130.226087,9484.8,395.200000,790.400000
139504,2025-03-05,2025-03-14,Air,Tap,3276.0,2735.0,13.833333,17.333333,4808.8,31.166667,154.293048,9617.6,400.733333,801.466667
139505,2025-03-05,2025-03-14,Air,Lufthansa,3276.0,2858.0,13.833333,15.500000,4907.2,29.333333,167.290909,9814.4,408.933333,817.866667
139506,2025-03-05,2025-03-14,Air,Tap,3276.0,3305.0,13.833333,13.333333,5264.8,27.166667,193.796319,10529.6,438.733333,877.466667
139507,2025-03-05,2025-03-14,Air,Iberia,3276.0,4802.0,13.833333,13.333333,6462.4,27.166667,237.879755,12924.8,538.533333,1077.066667
139774,2025-03-05,2025-03-14,Tap,Turkish,3386.0,2489.0,13.750000,31.750000,4700.0,45.500000,103.296703,9400.0,391.666667,783.333333
139775,2025-03-05,2025-03-14,Tap,Turkish,3386.0,2489.0,13.750000,33.333333,4700.0,47.083333,99.823009,9400.0,391.666667,783.333333
139776,2025-03-05,2025-03-14,Tap,Avianca,3386.0,2545.0,13.750000,20.666667,4744.8,34.416667,137.863438,9489.6,395.400000,790.800000
139777,2025-03-05,2025-03-14,Tap,Avianca and Gol,3386.0,2652.0,13.750000,22.583333,4830.4,36.333333,132.946789,9660.8,402.533333,805.066667
139778,2025-03-05,2025-03-14,Tap,Tap,3386.0,2735.0,13.750000,17.333333,4896.8,31.083333,157.537802,9793.6,408.066667,816.133333
139779,2025-03-05,2025-03-14,Tap,Lufthansa,3386.0,2858.0,13.750000,15.500000,4995.2,29.250000,170.776068,9990.4,416.266667,832.533333
139780,2025-03-05,2025-03-14,Tap,Tap,3386.0,3305.0,13.750000,13.333333,5352.8,27.083333,197.641846,10705.6,446.066667,892.133333
139781,2025-03-05,2025-03-14,Tap,Iberia,3386.0,4802.0,13.750000,13.333333,6550.4,27.083333,241.860923,13100.8,545.866667,1091.733333

In [5]:
lane[
    (lane['destiny_country_ida']=='Thailand') &
    (lane['travel_date_volta'] > lane['travel_date_ida'])
].pivot_table(index='travel_date_ida',columns='travel_date_volta',values='price_for_two',aggfunc=['min'],margins=True).style.background_gradient(cmap='coolwarm',axis=None).format("{:.2f}")

In [6]:

lane[
    (lane['destiny_country_ida']=='Thailand') &
    (lane['travel_date_volta'].astype(str) == '2025-05-12') &
    (lane['travel_date_ida'].astype(str) == '2025-05-01')
][[
    'travel_date_ida'
    ,'travel_date_volta'
    ,'companies_ida'
    ,'companies_volta'
    ,'price_ida'
    ,'price_volta'
    ,'total_hours_ida'
    ,'total_hours_volta'
    ,'total_price'
    ,'total_hours'
    ,'price_per_hour'
    ,'price_for_two'
    ,'12_times_price'
    ,'12_times_price_for_two'
    ,'total_hours_ida'
    ,'total_hours_volta'
]]

,travel_date_ida,travel_date_volta,companies_ida,companies_volta,price_ida,price_volta,total_hours_ida,total_hours_volta,total_price,total_hours,price_per_hour,price_for_two,12_times_price,12_times_price_for_two,total_hours_ida,total_hours_volta
199436,2025-05-01,2025-05-12,LATAM and Austrian,Ethiopian,4260.0,5116.0,34.833333,24.500000,7500.8,59.333333,126.417978,15001.6,625.066667,1250.133333,34.833333,24.500000
199437,2025-05-01,2025-05-12,LATAM and Austrian,Ethiopian,4260.0,5130.0,34.833333,24.500000,7512.0,59.333333,126.606742,15024.0,626.000000,1252.000000,34.833333,24.500000
199438,2025-05-01,2025-05-12,LATAM and Austrian,Finnair and LATAM,4260.0,5407.0,34.833333,31.666667,7733.6,66.500000,116.294737,15467.2,644.466667,1288.933333,34.833333,31.666667
199439,2025-05-01,2025-05-12,LATAM and Austrian,Finnair and LATAM,4260.0,5414.0,34.833333,31.666667,7739.2,66.500000,116.378947,15478.4,644.933333,1289.866667,34.833333,31.666667
199440,2025-05-01,2025-05-12,LATAM and Austrian,Emirates,4260.0,6008.0,34.833333,24.083333,8214.4,58.916667,139.424045,16428.8,684.533333,1369.066667,34.833333,24.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207307,2025-05-01,2025-05-12,Emirates,Emirates and Gol,5887.0,6853.0,25.166667,26.083333,10192.0,51.250000,198.868293,20384.0,849.333333,1698.666667,25.166667,26.083333
207308,2025-05-01,2025-05-12,Emirates,Qatar,5887.0,7423.0,25.166667,23.833333,10648.0,49.000000,217.306122,21296.0,887.333333,1774.666667,25.166667,23.833333
207309,2025-05-01,2025-05-12,Emirates,Qatar,5887.0,7443.0,25.166667,23.833333,10664.0,49.000000,217.632653,21328.0,888.666667,1777.333333,25.166667,23.833333
207310,2025-05-01,2025-05-12,Emirates,SWISS,5887.0,9545.0,25.166667,26.333333,12345.6,51.500000,239.720388,24691.2,1028.800000,2057.600000,25.166667,26.333333
207311,2025-05-01,2025-05-12,Emirates,SWISS,5887.0,9561.0,25.166667,26.333333,12358.4,51.500000,239.968932,24716.8,1029.866667,2059.733333,25.166667,26.333333

In [7]:
lane[
    (lane['destiny_country_ida']=='Brazil') &
    (lane['destiny_city_ida'] == 'Sao Luis') &
    (lane['travel_date_volta'] > lane['travel_date_ida'])
].pivot_table(index='travel_date_ida',columns='travel_date_volta',values='price_for_two',aggfunc=['mean'],margins=True).style.background_gradient(cmap='coolwarm',axis=None).format("{:.2f}")

In [8]:

lane[
    (lane['destiny_country_ida']=='Brazil') 
    & (lane['destiny_city_ida'] == 'Sao Luis')
    #& (lane['travel_date_volta'].astype(str) == '2025-05-12') 
    #& (lane['travel_date_ida'].astype(str) == '2025-05-01')
][[
    'destiny_city_ida'
    ,'travel_date_ida'
    ,'travel_date_volta'
    ,'companies_ida'
    ,'companies_volta'
    ,'price_ida'
    ,'price_volta'
    ,'total_hours_ida'
    ,'total_hours_volta'
    ,'total_price'
    ,'total_hours'
    ,'price_per_hour'
    ,'price_for_two'
    ,'12_times_price'
    ,'12_times_price_for_two'
    ,'total_hours_ida'
    ,'total_hours_volta'
]]

,destiny_city_ida,travel_date_ida,travel_date_volta,companies_ida,companies_volta,price_ida,price_volta,total_hours_ida,total_hours_volta,total_price,total_hours,price_per_hour,price_for_two,12_times_price,12_times_price_for_two,total_hours_ida,total_hours_volta
64,Sao Luis,2024-11-10,2024-11-20,Gol,LATAM,742.0,651.0,5.750000,7.583333,1114.4,13.333333,83.580000,2228.8,92.866667,185.733333,5.750000,7.583333
65,Sao Luis,2024-11-10,2024-11-20,Gol,LATAM,742.0,651.0,5.750000,5.166667,1114.4,10.916667,102.082443,2228.8,92.866667,185.733333,5.750000,5.166667
66,Sao Luis,2024-11-10,2024-11-20,Gol,LATAM,742.0,651.0,5.750000,7.583333,1114.4,13.333333,83.580000,2228.8,92.866667,185.733333,5.750000,7.583333
67,Sao Luis,2024-11-10,2024-11-20,Gol,LATAM,742.0,651.0,5.750000,5.166667,1114.4,10.916667,102.082443,2228.8,92.866667,185.733333,5.750000,5.166667
68,Sao Luis,2024-11-10,2024-11-20,Gol,Azul,742.0,1069.0,5.750000,5.916667,1448.8,11.666667,124.182857,2897.6,120.733333,241.466667,5.750000,5.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416047,Sao Luis,2024-11-10,2024-10-20,Azul,Azul,1003.0,1225.0,5.583333,6.916667,1782.4,12.500000,142.592000,3564.8,148.533333,297.066667,5.583333,6.916667
3416048,Sao Luis,2024-11-10,2024-11-20,Azul,LATAM,1003.0,684.0,5.583333,6.083333,1349.6,11.666667,115.680000,2699.2,112.466667,224.933333,5.583333,6.083333
3416049,Sao Luis,2024-11-10,2024-11-20,Azul,Azul,1003.0,935.0,5.583333,6.916667,1550.4,12.500000,124.032000,3100.8,129.200000,258.400000,5.583333,6.916667
3416050,Sao Luis,2024-11-10,2024-11-20,Azul,Azul,1003.0,935.0,5.583333,9.666667,1550.4,15.250000,101.665574,3100.8,129.200000,258.400000,5.583333,9.666667
3416051,Sao Luis,2024-11-10,2024-11-20,Azul,Azul,1003.0,936.0,5.583333,6.250000,1551.2,11.833333,131.087324,3102.4,129.266667,258.533333,5.583333,6.250000

In [9]:

lane[
    (lane['destiny_country_ida']=='Brazil') 
    #& (lane['destiny_city_ida'] == 'Cancun')
    #& (lane['travel_date_volta'].astype(str) == '2025-05-12') 
    #& (lane['travel_date_ida'].astype(str) == '2025-05-01')
].groupby(
    ['destiny_city_ida']
)['origin_city_ida'].count()

destiny_city_ida
Fortaleza    240
Salvador      88
Sao Luis     540
Teresina     210
Name: origin_city_ida, dtype: int64

In [10]:
lane[lane['destiny_city_ida']=='Los Angeles'].groupby('travel_date_ida')['price_ida'].count()

travel_date_ida
2025-03-01    14712
2025-03-02    14712
2025-03-03     9808
2025-03-04    17164
2025-03-05    13486
              ...
2025-06-13     9808
2025-06-14    19616
2025-06-15    12260
2025-06-16    13486
2025-06-17    36780
Name: price_ida, Length: 88, dtype: int64

In [3]:
lane[
    (lane['destiny_city_ida']=='Barcelona') &
    (lane['travel_date_volta'] > lane['travel_date_ida'])
].pivot_table(index='travel_date_ida',columns='travel_date_volta',values='price_for_two',aggfunc=['min'],margins=True).style.background_gradient(cmap='coolwarm',axis=None).format("{:.2f}")